version: 2
jobs:
  build:
    # Note: We have to use 'machine' here until https://discuss.circleci.com/t/can-docker-images-be-preserved-between-jobs-in-a-workflow-without-a-manual-load-save/23388
    #       is resolved.
    #       "machine" is recommended at https://support.circleci.com/hc/en-us/articles/360007324514-How-can-I-mount-volumes-to-docker-containers-
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Bulid docker image
          command: make docker_build
      - run:
          name: Build pdf from latex
          command: make docker_run TARGET=build
      - store_artifacts:
          path: resume.pdf
